version: "3"

volumes:
  mongodb_volume:

services:
  flask:
    build: Flask/
    restart: always
    ports:
      - 80:8080
    environment:
      - TZ=Europe/Moscow
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    restart: always
